console_title_template = "{{if .Root}}[ADMIN]{{end}} {{.AbsolutePWD}} ({{.Shell}})"
final_space = true

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "#83A598"
  template = "{{ .AbsolutePWD }}"

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "#8EC07C"
  template = "❯"

[transient_prompt]
  foreground = "#8EC07C"
  template = "❯ "

